//! Large-scale hybrid workspace fixture for CI stress tests.
//!
//! Generates approximately 800,000 files under a single root directory:
//! - 70% dependency files (node_modules, vendor, target, .git, __pycache__, .gradle, .m2)
//! - 15% gitignored files (*.log, *.tmp, build/, dist/, .env*, etc.)
//! - 15% user source/config files with unique searchable identifiers.
//!
//! Performance considerations:
//! - All file metadata is pre-generated into an in-memory Vec, then written in
//!   parallel via `rayon`.
//! - Directories are deduplicated and created in parallel before file writes.
//! - File contents are small (tens to hundreds of bytes) to minimize I/O.

#![allow(dead_code, unused)]

use std::collections::HashSet;
use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use rayon::prelude::*;

// ---------------------------------------------------------------------------
// Targets
// ---------------------------------------------------------------------------

/// Approximate total files to generate.
const TARGET_TOTAL: usize = 800_000;

/// 70% dependency files.
const TARGET_DEP: usize = 560_000;

/// 15% ignored files.
const TARGET_IGNORED: usize = 120_000;

/// 15% user files.
const TARGET_USER: usize = 120_000;

// ---------------------------------------------------------------------------
// Content templates
// ---------------------------------------------------------------------------

const ROOT_GITIGNORE: &str = r#"
# Generated by HybridWorkspace
*.log
*.tmp
*.swp
*.bak
build/
dist/
out/
.env*
.secret*
node_modules/
target/
__pycache__/
.gradle/
.m2/
"#;

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

#[derive(Clone, Debug)]
struct FileSpec {
    path: PathBuf,
    content: Vec<u8>,
    category: FileCategory,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum FileCategory {
    Dep,
    Ignored,
    User,
}

/// Deterministic pseudo-random byte generator (LCG).
fn pseudo_random_bytes(seed: usize, len: usize) -> Vec<u8> {
    let mut buf = Vec::with_capacity(len);
    let charset =
        b"abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789\n /{}[]();:,.=+-_";
    let mut state = seed as u64;
    for _ in 0..len {
        state = state
            .wrapping_mul(6_364_136_223_846_793_005)
            .wrapping_add(1);
        buf.push(charset[(state % charset.len() as u64) as usize]);
    }
    buf
}

/// Content for a dependency file.
fn dep_content(seed: usize) -> Vec<u8> {
    let len = 50 + (seed % 200);
    pseudo_random_bytes(seed, len)
}

/// Content for an ignored file.
fn ignored_content(seed: usize) -> Vec<u8> {
    let len = 20 + (seed % 100);
    pseudo_random_bytes(seed ^ 0xDEAD_BEEF, len)
}

/// Content for a generic user file.
fn user_content(id: usize) -> Vec<u8> {
    format!(
        "// HYBRID_USER_FILE_ID_{id:08}\n// search_marker_{id:08}\n// This file is part of the CI stress test workspace.\n",
    )
    .into_bytes()
}

/// Content for a user file with language-appropriate syntax.
fn user_content_for(id: usize, ext: &str) -> Vec<u8> {
    let text = match ext {
        "rs" => format!(
            "// HYBRID_USER_FILE_ID_{id:08}\npub fn function_{id:08}() {{}}\n// search_marker_{id:08}\n"
        ),
        "ts" | "js" => format!(
            "// HYBRID_USER_FILE_ID_{id:08}\nexport function func_{id:08}() {{}}\n// search_marker_{id:08}\n"
        ),
        "py" => format!(
            "# HYBRID_USER_FILE_ID_{id:08}\ndef function_{id:08}():\n    pass\n# search_marker_{id:08}\n"
        ),
        "go" => format!(
            "// HYBRID_USER_FILE_ID_{id:08}\npackage main\nfunc Func{id:08}() {{}}\n// search_marker_{id:08}\n"
        ),
        "java" => format!(
            "// HYBRID_USER_FILE_ID_{id:08}\npublic class Class{id:08} {{}}\n// search_marker_{id:08}\n"
        ),
        "c" | "cpp" | "h" | "hpp" => format!(
            "/* HYBRID_USER_FILE_ID_{id:08} */\nvoid func_{id:08}() {{}}\n/* search_marker_{id:08} */\n"
        ),
        "toml" => format!(
            "# HYBRID_USER_FILE_ID_{id:08}\n[package]\nname = \"pkg_{id:08}\"\n# search_marker_{id:08}\n"
        ),
        "yaml" | "yml" => format!(
            "# HYBRID_USER_FILE_ID_{id:08}\nkey: value_{id:08}\n# search_marker_{id:08}\n"
        ),
        "json" => format!(
            "{{\"id\":\"{id:08}\",\"marker\":\"search_marker_{id:08}\",\"type\":\"user\"}}\n"
        ),
        "md" => format!(
            "# Doc {id:08}\n\nIdentifier: `HYBRID_USER_FILE_ID_{id:08}`\nMarker: `search_marker_{id:08}`\n"
        ),
        "txt" => format!(
            "HYBRID_USER_FILE_ID_{id:08}\nsearch_marker_{id:08}\n"
        ),
        _ => format!(
            "// HYBRID_USER_FILE_ID_{id:08}\n// search_marker_{id:08}\n"
        ),
    };
    text.into_bytes()
}

// ---------------------------------------------------------------------------
// Spec generators
// ---------------------------------------------------------------------------

fn generate_dep_specs(root: &Path) -> Vec<FileSpec> {
    let mut specs = Vec::with_capacity(TARGET_DEP);

    // 1. node_modules – ~150,000 files (3,000 packages × ~50 files)
    let npm_root = root.join("node_modules");
    for pkg_idx in 0..3_000 {
        let pkg_dir = npm_root.join(format!("pkg_{pkg_idx:04}"));

        // Metadata
        for (name, seed_off) in [
            ("package.json", 0),
            ("README.md", 1),
            ("LICENSE", 2),
            ("index.js", 3),
            (".travis.yml", 6),
            (".eslintrc.json", 7),
            (".prettierrc", 8),
        ] {
            specs.push(FileSpec {
                path: pkg_dir.join(name),
                content: dep_content(pkg_idx ^ seed_off),
                category: FileCategory::Dep,
            });
        }

        // lib/*.js (15)
        for i in 0..15 {
            specs.push(FileSpec {
                path: pkg_dir.join("lib").join(format!("{i}.js")),
                content: dep_content(pkg_idx * 100 + i),
                category: FileCategory::Dep,
            });
        }
        // dist/*.js (10)
        for i in 0..10 {
            specs.push(FileSpec {
                path: pkg_dir.join("dist").join(format!("{i}.js")),
                content: dep_content(pkg_idx * 100 + i + 1_000),
                category: FileCategory::Dep,
            });
        }
        // test/*.js (10)
        for i in 0..10 {
            specs.push(FileSpec {
                path: pkg_dir.join("test").join(format!("{i}.js")),
                content: dep_content(pkg_idx * 100 + i + 2_000),
                category: FileCategory::Dep,
            });
        }
        // node_modules/.bin/ (2)
        for i in 0..2 {
            specs.push(FileSpec {
                path: pkg_dir
                    .join("node_modules")
                    .join(".bin")
                    .join(format!("bin{pkg_idx}_{i}")),
                content: dep_content(pkg_idx ^ (4 + i)),
                category: FileCategory::Dep,
            });
        }
        // Extra .js (7) to reach ~50 per package
        for i in 0..7 {
            specs.push(FileSpec {
                path: pkg_dir.join(format!("extra{i}.js")),
                content: dep_content(pkg_idx * 100 + i + 3_000),
                category: FileCategory::Dep,
            });
        }
    }

    // 2. vendor – ~150,000 files
    // go vendor (1,000 packages × 50)
    let go_root = root.join("vendor").join("go");
    for pkg_idx in 0..1_000 {
        let pkg_dir = go_root.join(format!("go_pkg_{pkg_idx:04}"));
        for file_idx in 0..50 {
            specs.push(FileSpec {
                path: pkg_dir.join(format!("file_{file_idx:02}.go")),
                content: dep_content(pkg_idx * 1_000 + file_idx + 10_000),
                category: FileCategory::Dep,
            });
        }
    }
    // rust vendor (1,000 crates × 50)
    let rust_root = root.join("vendor").join("rust");
    for pkg_idx in 0..1_000 {
        let pkg_dir = rust_root.join(format!("rust_crate_{pkg_idx:04}"));
        for file_idx in 0..50 {
            specs.push(FileSpec {
                path: pkg_dir.join(format!("file_{file_idx:02}.rs")),
                content: dep_content(pkg_idx * 1_000 + file_idx + 20_000),
                category: FileCategory::Dep,
            });
        }
    }
    // php vendor (1,000 packages × 50)
    let php_root = root.join("vendor").join("php");
    for pkg_idx in 0..1_000 {
        let pkg_dir = php_root.join(format!("php_pkg_{pkg_idx:04}"));
        for file_idx in 0..50 {
            specs.push(FileSpec {
                path: pkg_dir.join(format!("file_{file_idx:02}.php")),
                content: dep_content(pkg_idx * 1_000 + file_idx + 30_000),
                category: FileCategory::Dep,
            });
        }
    }

    // 3. target – ~100,000 files (50k debug + 50k release)
    let target_root = root.join("target");
    for (target_name, base_seed) in [("debug", 40_000), ("release", 50_000)] {
        let target_dir = target_root.join(target_name).join("deps");
        for i in 0..50_000 {
            let hash = format!("{:016x}", i * 0x9E37_79B9_7F4A_7C15);
            let stem = format!("lib{i}-{hash}");
            specs.push(FileSpec {
                path: target_dir.join(format!("{stem}.rlib")),
                content: dep_content(base_seed + i),
                category: FileCategory::Dep,
            });
        }
    }

    // 4. .git – ~40,000 files
    let git_root = root.join(".git");
    for i in 0..39_000 {
        let dir = format!("{:02x}", i % 256);
        let file = format!("{:038x}", i);
        specs.push(FileSpec {
            path: git_root.join("objects").join(dir).join(file),
            content: dep_content(i + 100_000),
            category: FileCategory::Dep,
        });
    }
    for i in 0..100 {
        specs.push(FileSpec {
            path: git_root
                .join("refs")
                .join("heads")
                .join(format!("branch_{i:03}")),
            content: dep_content(i + 200_000),
            category: FileCategory::Dep,
        });
    }
    for name in &["HEAD", "config", "description"] {
        specs.push(FileSpec {
            path: git_root.join(name),
            content: dep_content(name.len() + 300_000),
            category: FileCategory::Dep,
        });
    }

    // 5. __pycache__ – ~40,000 files (200 dirs × 200 files)
    let pyc_root = root.join("__pycache__");
    for dir_idx in 0..200 {
        let dir = pyc_root.join(format!("module_{dir_idx:03}"));
        for file_idx in 0..200 {
            specs.push(FileSpec {
                path: dir.join(format!("{file_idx:03}.cpython-311.pyc")),
                content: dep_content(dir_idx * 1_000 + file_idx + 400_000),
                category: FileCategory::Dep,
            });
        }
    }

    // 6. .gradle – ~40,000 files (500 dirs × 80 files)
    let gradle_root = root.join(".gradle");
    for dir_idx in 0..500 {
        let dir = gradle_root.join(format!("cache_{dir_idx:03}"));
        for file_idx in 0..80 {
            specs.push(FileSpec {
                path: dir.join(format!("file_{file_idx:03}.bin")),
                content: dep_content(dir_idx * 1_000 + file_idx + 500_000),
                category: FileCategory::Dep,
            });
        }
    }

    // 7. .m2 – ~40,000 files (5,000 pkgs × 8 files)
    let m2_root = root.join(".m2").join("repository");
    for pkg_idx in 0..5_000 {
        let pkg_dir = m2_root
            .join("com")
            .join("example")
            .join(format!("pkg_{pkg_idx:04}"))
            .join("1.0.0");
        for (ext, seed_off) in [
            ("jar", 0),
            ("pom", 1),
            ("sha1", 2),
            ("md5", 3),
            ("xml", 4),
            ("properties", 5),
            ("lastUpdated", 6),
        ] {
            specs.push(FileSpec {
                path: pkg_dir.join(format!("pkg_{pkg_idx}-1.0.0.{ext}")),
                content: dep_content(pkg_idx * 100 + seed_off + 600_000),
                category: FileCategory::Dep,
            });
        }
        // sources.jar
        specs.push(FileSpec {
            path: pkg_dir.join(format!("pkg_{pkg_idx}-1.0.0-sources.jar")),
            content: dep_content(pkg_idx + 700_000),
            category: FileCategory::Dep,
        });
    }

    specs
}

fn generate_ignored_specs(root: &Path) -> Vec<FileSpec> {
    let mut specs = Vec::with_capacity(TARGET_IGNORED);

    // *.log – 20,000
    for i in 0..20_000 {
        specs.push(FileSpec {
            path: root.join("logs").join(format!("app_{i:05}.log")),
            content: ignored_content(i),
            category: FileCategory::Ignored,
        });
    }

    // *.tmp – 20,000
    for i in 0..20_000 {
        specs.push(FileSpec {
            path: root.join("tmp").join(format!("temp_{i:05}.tmp")),
            content: ignored_content(i + 20_000),
            category: FileCategory::Ignored,
        });
    }

    // *.swp – 10,000
    for i in 0..10_000 {
        specs.push(FileSpec {
            path: root.join("src").join(format!(".file_{i:05}.swp")),
            content: ignored_content(i + 40_000),
            category: FileCategory::Ignored,
        });
    }

    // *.bak – 10,000
    for i in 0..10_000 {
        specs.push(FileSpec {
            path: root.join("backups").join(format!("backup_{i:05}.bak")),
            content: ignored_content(i + 50_000),
            category: FileCategory::Ignored,
        });
    }

    // build/ – 20,000 files (200 dirs × 100)
    for dir_idx in 0..200 {
        let dir = root.join("build").join(format!("project_{dir_idx:03}"));
        for file_idx in 0..100 {
            specs.push(FileSpec {
                path: dir.join(format!("out_{file_idx:03}.o")),
                content: ignored_content(dir_idx * 1_000 + file_idx + 60_000),
                category: FileCategory::Ignored,
            });
        }
    }

    // dist/ – 20,000 files (200 dirs × 100)
    for dir_idx in 0..200 {
        let dir = root.join("dist").join(format!("bundle_{dir_idx:03}"));
        for file_idx in 0..100 {
            specs.push(FileSpec {
                path: dir.join(format!("chunk_{file_idx:03}.js")),
                content: ignored_content(dir_idx * 1_000 + file_idx + 80_000),
                category: FileCategory::Ignored,
            });
        }
    }

    // out/ – 10,000 files (100 dirs × 100)
    for dir_idx in 0..100 {
        let dir = root.join("out").join(format!("output_{dir_idx:03}"));
        for file_idx in 0..100 {
            specs.push(FileSpec {
                path: dir.join(format!("file_{file_idx:03}.class")),
                content: ignored_content(dir_idx * 1_000 + file_idx + 100_000),
                category: FileCategory::Ignored,
            });
        }
    }

    // .env* – 5,000
    for i in 0..5_000 {
        specs.push(FileSpec {
            path: root.join(format!(".env.{i}")),
            content: ignored_content(i + 110_000),
            category: FileCategory::Ignored,
        });
    }

    // .secret* – 5,000
    for i in 0..5_000 {
        specs.push(FileSpec {
            path: root.join(format!(".secret.{i}")),
            content: ignored_content(i + 115_000),
            category: FileCategory::Ignored,
        });
    }

    specs
}

fn generate_user_specs(root: &Path) -> Vec<FileSpec> {
    let mut specs = Vec::with_capacity(TARGET_USER);

    let source_exts = &["rs", "ts", "js", "py", "go", "java", "c", "cpp", "h", "hpp"];
    let config_exts = &["toml", "yaml", "yml", "json", "md", "txt"];
    let hidden_names = &[
        ".bashrc",
        ".zshrc",
        ".vimrc",
        ".gitconfig",
        ".editorconfig",
        ".dockerignore",
    ];
    let doc_names = &["README.md", "CHANGELOG.md", "CONTRIBUTING.md", "LICENSE"];

    // Source files – 60,000 (6,000 per ext)
    let src_root = root.join("src");
    for (ext_idx, ext) in source_exts.iter().enumerate() {
        for i in 0..6_000 {
            let id = ext_idx * 6_000 + i;
            specs.push(FileSpec {
                path: src_root.join(ext).join(format!("file_{id:05}.{ext}")),
                content: user_content_for(id, ext),
                category: FileCategory::User,
            });
        }
    }

    // Config files – 30,000 (5,000 per ext)
    let config_root = root.join("config");
    for (ext_idx, ext) in config_exts.iter().enumerate() {
        for i in 0..5_000 {
            let id = 60_000 + ext_idx * 5_000 + i;
            specs.push(FileSpec {
                path: config_root.join(ext).join(format!("cfg_{id:05}.{ext}")),
                content: user_content_for(id, ext),
                category: FileCategory::User,
            });
        }
    }

    // Hidden files – 20,004 (~3,334 each)
    let home_root = root.join("home");
    for (name_idx, name) in hidden_names.iter().enumerate() {
        let count = if name_idx == 0 { 3_336 } else { 3_334 };
        for i in 0..count {
            let id = 90_000 + name_idx * 3_334 + i;
            specs.push(FileSpec {
                path: home_root.join(format!("user_{i:04}")).join(name),
                content: user_content_for(id, "txt"),
                category: FileCategory::User,
            });
        }
    }

    // Documents – 10,000 (2,500 each)
    let docs_root = root.join("docs");
    for (name_idx, name) in doc_names.iter().enumerate() {
        for i in 0..2_500 {
            let id = 110_000 + name_idx * 2_500 + i;
            specs.push(FileSpec {
                path: docs_root.join(format!("project_{i:04}")).join(name),
                content: user_content_for(id, "md"),
                category: FileCategory::User,
            });
        }
    }

    specs
}

// ---------------------------------------------------------------------------
// Parallel I/O helpers
// ---------------------------------------------------------------------------

fn ensure_dirs(specs: &[FileSpec]) -> Result<()> {
    let dirs: Vec<PathBuf> = specs
        .iter()
        .filter_map(|s| s.path.parent().map(|p| p.to_path_buf()))
        .collect::<HashSet<_>>()
        .into_iter()
        .collect();

    dirs.into_par_iter().try_for_each(|dir| {
        fs::create_dir_all(&dir)
            .with_context(|| format!("Failed to create directory: {}", dir.display()))?;
        Ok::<(), anyhow::Error>(())
    })?;

    Ok(())
}

fn write_specs_parallel(specs: &[FileSpec]) -> Result<()> {
    specs.par_iter().try_for_each(|spec| {
        fs::write(&spec.path, &spec.content)
            .with_context(|| format!("Failed to write file: {}", spec.path.display()))?;
        Ok::<(), anyhow::Error>(())
    })?;
    Ok(())
}

// ---------------------------------------------------------------------------
// HybridWorkspace
// ---------------------------------------------------------------------------

#[derive(Debug)]
pub struct HybridWorkspace {
    pub root: PathBuf,
    /// 15% user files (searchable, should be indexed).
    pub user_files: Vec<PathBuf>,
    /// 15% ignored files (exist on disk but filtered by ignore rules).
    pub ignored_files: Vec<PathBuf>,
    /// 70% dependency files (should be skipped or deprioritized).
    pub dep_files: Vec<PathBuf>,
}

impl HybridWorkspace {
    /// Generate the complete hybrid workspace under `root`.
    ///
    /// Creates approximately 800,000 files split across three categories.
    /// The operation is parallelized with `rayon` and typically completes
    /// within a few minutes on a modern SSD.
    pub fn generate(root: &Path) -> Result<Self> {
        fs::create_dir_all(root)
            .with_context(|| format!("Failed to create root: {}", root.display()))?;

        // Pre-generate all file specs sequentially (fast, deterministic).
        let mut specs = Vec::with_capacity(TARGET_TOTAL);
        specs.extend(generate_dep_specs(root));
        specs.extend(generate_ignored_specs(root));
        specs.extend(generate_user_specs(root));

        // Write root .gitignore
        let gitignore_path = root.join(".gitignore");
        fs::write(&gitignore_path, ROOT_GITIGNORE)
            .with_context(|| format!("Failed to write {}", gitignore_path.display()))?;

        // Write a few nested .gitignore files for realism.
        let nested_gitignores = vec![
            (root.join("src").join(".gitignore"), "*.swp\n*.bak\n"),
            (root.join("build").join(".gitignore"), "*\n"),
            (root.join("dist").join(".gitignore"), "*\n"),
            (root.join("logs").join(".gitignore"), "*.log\n"),
            (root.join("node_modules").join(".gitignore"), "*\n"),
            (root.join("target").join(".gitignore"), "*\n"),
        ];
        for (path, rules) in nested_gitignores {
            if let Some(parent) = path.parent() {
                let _ = fs::create_dir_all(parent);
            }
            let _ = fs::write(&path, rules);
        }

        // Ensure all parent directories exist, then write files in parallel.
        ensure_dirs(&specs)?;
        write_specs_parallel(&specs)?;

        // Categorize paths for the caller.
        let mut user_files = Vec::new();
        let mut ignored_files = Vec::new();
        let mut dep_files = Vec::new();

        for spec in specs {
            match spec.category {
                FileCategory::User => user_files.push(spec.path),
                FileCategory::Ignored => ignored_files.push(spec.path),
                FileCategory::Dep => dep_files.push(spec.path),
            }
        }

        Ok(Self {
            root: root.to_path_buf(),
            user_files,
            ignored_files,
            dep_files,
        })
    }

    /// Simulate a `git clone` by creating a small repository subtree.
    ///
    /// Creates `.git/objects`, refs, a few source files and a `README.md`.
    /// New files are appended to the internal tracking vectors.
    pub fn simulate_git_clone(&mut self, repo_name: &str) -> Result<Vec<PathBuf>> {
        let repo_root = self.root.join(repo_name);
        fs::create_dir_all(&repo_root)?;

        let mut created = Vec::new();

        // .git directory (dep files)
        let git_dir = repo_root.join(".git");
        for i in 0..500 {
            let dir = format!("{:02x}", i % 256);
            let file = format!("{:038x}", i);
            let path = git_dir.join("objects").join(dir).join(file);
            fs::create_dir_all(path.parent().unwrap())?;
            fs::write(&path, dep_content(i))?;
            created.push(path.clone());
            self.dep_files.push(path);
        }
        for name in &["HEAD", "config", "description"] {
            let path = git_dir.join(name);
            fs::write(&path, dep_content(name.len()))?;
            created.push(path.clone());
            self.dep_files.push(path);
        }

        // Source files (user files)
        let src_dir = repo_root.join("src");
        fs::create_dir_all(&src_dir)?;
        for i in 0..20 {
            let path = src_dir.join(format!("file_{i:02}.rs"));
            fs::write(&path, user_content_for(i, "rs"))?;
            created.push(path.clone());
            self.user_files.push(path);
        }

        // README.md (user file)
        let readme = repo_root.join("README.md");
        fs::write(&readme, user_content_for(0, "md"))?;
        created.push(readme.clone());
        self.user_files.push(readme);

        // Repo-level .gitignore (not tracked as ignored; it's a rules file)
        let gi = repo_root.join(".gitignore");
        fs::write(&gi, "*.log\nbuild/\n")?;
        created.push(gi);

        Ok(created)
    }

    /// Simulate `npm install` by creating a package directory under
    /// `node_modules/` populated with `file_count` files.
    ///
    /// Files are written in parallel and appended to `dep_files`.
    pub fn simulate_npm_install(
        &mut self,
        pkg_name: &str,
        file_count: usize,
    ) -> Result<Vec<PathBuf>> {
        let pkg_dir = self.root.join("node_modules").join(pkg_name);
        let mut paths = Vec::with_capacity(file_count);

        for i in 0..file_count {
            let subdir = pkg_dir.join(format!("lib_{}", i % 10));
            let path = subdir.join(format!("file_{i}.js"));
            paths.push(path);
        }

        // Pre-create subdirectories.
        let dirs: Vec<PathBuf> = paths
            .iter()
            .filter_map(|p| p.parent().map(|x| x.to_path_buf()))
            .collect::<HashSet<_>>()
            .into_iter()
            .collect();
        for dir in &dirs {
            fs::create_dir_all(dir)?;
        }

        // Write in parallel.
        paths.par_iter().enumerate().try_for_each(|(i, path)| {
            fs::write(path, dep_content(i))
                .with_context(|| format!("npm install write: {}", path.display()))?;
            Ok::<(), anyhow::Error>(())
        })?;

        self.dep_files.extend(paths.clone());
        Ok(paths)
    }

    /// Create a user file at a path relative to the workspace root.
    ///
    /// The file is appended to `user_files`.
    pub fn user_create_file(&mut self, rel_path: &str, content: &str) -> Result<PathBuf> {
        let path = self.root.join(rel_path);
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent).with_context(|| format!("mkdir {}", parent.display()))?;
        }
        fs::write(&path, content.as_bytes())
            .with_context(|| format!("write {}", path.display()))?;
        self.user_files.push(path.clone());
        Ok(path)
    }

    /// Delete a file from the workspace and remove it from internal tracking.
    pub fn user_delete_file(&mut self, path: &Path) -> Result<()> {
        fs::remove_file(path).with_context(|| format!("remove {}", path.display()))?;
        self.user_files.retain(|p| p != path);
        self.ignored_files.retain(|p| p != path);
        self.dep_files.retain(|p| p != path);
        Ok(())
    }

    /// Rename a file in the workspace and update internal tracking.
    pub fn user_rename_file(&mut self, from: &Path, to: &Path) -> Result<()> {
        if let Some(parent) = to.parent() {
            fs::create_dir_all(parent).with_context(|| format!("mkdir {}", parent.display()))?;
        }
        fs::rename(from, to)
            .with_context(|| format!("rename {} -> {}", from.display(), to.display()))?;

        let update = |vec: &mut Vec<PathBuf>| {
            if let Some(pos) = vec.iter().position(|p| p == from) {
                vec[pos] = to.to_path_buf();
            }
        };

        update(&mut self.user_files);
        update(&mut self.ignored_files);
        update(&mut self.dep_files);
        Ok(())
    }

    /// Remove the entire workspace root directory.
    pub fn cleanup(&self) -> Result<()> {
        fs::remove_dir_all(&self.root)
            .with_context(|| format!("cleanup {}", self.root.display()))?;
        Ok(())
    }

    /// Total number of tracked files.
    pub fn total_tracked(&self) -> usize {
        self.user_files.len() + self.ignored_files.len() + self.dep_files.len()
    }

    /// Return only the user files that should be indexed by fd-rdd.
    ///
    /// (Ignored and dependency files are excluded.)
    pub fn indexable_files(&self) -> &[PathBuf] {
        &self.user_files
    }

    /// Alias for `total_tracked` to match expected test API.
    pub fn total_file_count(&self) -> usize {
        self.total_tracked()
    }

    /// Sample up to `n` ignored file paths.
    pub fn sample_ignored_files(&self, n: usize) -> Vec<PathBuf> {
        self.ignored_files.iter().take(n).cloned().collect()
    }

    /// Sample up to `n` searchable (user) file paths.
    pub fn sample_searchable_files(&self, n: usize) -> Vec<PathBuf> {
        self.user_files.iter().take(n).cloned().collect()
    }
}
